apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: dbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          value: "root123"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: dbs
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    nodePort: 31004