apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: dbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Root123123"
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: sqlserver-data
          mountPath: /var/opt/mssql
      volumes:
      - name: sqlserver-data
        persistentVolumeClaim:
          claimName: sqlserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: dbs
spec:
  selector:
    app: sqlserver
  type: NodePort
  ports:
  - name: sqlserver-port
    port: 1433
    protocol: TCP
    targetPort: 1433
    nodePort: 31003
